import { Database } from "bun:sqlite";
import fs from "node:fs";
import path from "node:path";

const SQLITE_DIR = "./sqlite";
const MANIFEST_PATH = "./manifest.json";
const REPO = "josephT273/open-bible-data";
const TAG = process.env.GITHUB_REF_NAME || "latest"; // Fallback to 'latest' if not in CI

type BibleMeta = {
    id: string;
    name: string;
    language: string;
    language_short: string;
    description: string;
    file: string;
    size: number;
    url: string;
};

function generateManifest() {
    if (!fs.existsSync(SQLITE_DIR)) {
        console.error(`Directory ${SQLITE_DIR} does not exist. Run bible.ts first.`);
        process.exit(1);
    }

    const files = fs.readdirSync(SQLITE_DIR).filter((f) => f.endsWith(".sqlite"));
    const bibles: BibleMeta[] = [];

    console.log(`Found ${files.length} SQLite databases. Generating manifest...`);

    for (const file of files) {
        const dbPath = path.join(SQLITE_DIR, file);
        const db = new Database(dbPath, { readonly: true });

        try {
            // Read metadata generated by bible.ts
            const meta = db.prepare("SELECT * FROM metadata LIMIT 1").get() as any;

            if (meta) {
                bibles.push({
                    id: meta.shortname || meta.name || file.replace(".sqlite", ""),
                    name: meta.name || file,
                    language: meta.lang || "Unknown",
                    language_short: meta.lang_short || "",
                    description: meta.description || "",
                    file: file,
                    size: fs.statSync(dbPath).size,
                    url: `https://github.com/${REPO}/releases/download/${TAG}/${file}`,
                });
            } else {
                console.warn(`No metadata found in ${file}`);
            }
        } catch (e) {
            console.error(`Error reading metadata from ${file}:`, e);
        } finally {
            db.close();
        }
    }

    const manifest = {
        updated_at: new Date().toISOString(),
        release_tag: TAG,
        total: bibles.length,
        versions: bibles,
    };

    fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
    console.log(`Manifest successfully generated at ${MANIFEST_PATH} with ${bibles.length} Bibles.`);
}

generateManifest();
